version: 1
script: |
  mkdir -p AppDir
  cp -r dist/linux-unpacked/* AppDir/
  mkdir -p AppDir/usr/share/icons/hicolor/256x256/apps
  cp AppDir/icon.png AppDir/usr/share/icons/hicolor/256x256/apps/icon.png
AppDir:
  path: ./AppDir
  app_info:
    id: com.planet_ink.sip
    name: Sip
    icon: icon
    version: 3.1.6
    exec: Sip
    exec_args: "$@"
AppImage:
  arch: x86_64
  update-information: none