version: 1
script: |
  mkdir -p AppDir
  cp -r dist/linux-unpacked/* AppDir/
AppDir:
  path: ./AppDir
  app_info:
    id: com.planet_ink.sip
    name: Sip
    icon: icon.png
    version: 3.1.6
    exec: Sip
    exec_args: "$@"
AppImage:
  arch: x86_64
  update-information: none