name: Sip Cross-Platform Build

on:
  push:
    branches:
      - master
    tags:
      - 'v*'
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag name (e.g., v3.0.3)'
        required: true
        type: string

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        variant: [sip, socm]
        include:
          - os: ubuntu-latest
            variant: sip
            platform: linux
            build_cmd: dist:linux
            artifact_name: sip-linux
            product_name: Sip
          - os: ubuntu-latest
            variant: socm
            platform: linux
            build_cmd: distb:linux
            artifact_name: socm-linux
            product_name: SipOfCoffeeMud
          - os: windows-latest
            variant: sip
            platform: windows
            build_cmd: dist:win
            artifact_name: sip-windows
            product_name: Sip
          - os: windows-latest
            variant: socm
            platform: windows
            build_cmd: distb:win
            artifact_name: socm-windows
            product_name: SipOfCoffeeMud
          - os: macos-latest
            variant: sip
            platform: macos
            build_cmd: dist:mac
            artifact_name: sip-macos
            product_name: Sip
          - os: macos-latest
            variant: socm
            platform: macos
            build_cmd: distb:mac
            artifact_name: socm-macos
            product_name: SipOfCoffeeMud

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-npm-

      - name: Install Dependencies
        run: npm install

      - name: Install Linux Dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libfuse2 rpm jq ruby-dev build-essential
          sudo gem install fpm

      - name: Build Sip
        env:
          PRODUCT: ${{ matrix.product_name }}
        run: |
          if [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
            env -i PATH="$PATH" HOME="$HOME" npm run ${{ matrix.build_cmd }} -- --linux dir
            BINNAME="sip-mud-client"
            if [ "$PRODUCT" = "SipOfCoffeeMud" ]; then
              BINNAME="sip-of-coffeemud"
            fi
            VERSION=$(jq -r .version package.json)
            curl -L -o appimagetool https://github.com/AppImage/appimagetool/releases/download/continuous/appimagetool-x86_64.AppImage
            chmod +x appimagetool
            mkdir $PRODUCT.AppDir
            cp -r dist/linux-unpacked/* $PRODUCT.AppDir/
            cd $PRODUCT.AppDir
            echo '#!/bin/bash' > AppRun
            echo 'HERE="$(dirname "$(readlink -f "${0}")")"' >> AppRun
            echo 'exec "${HERE}/'"$BINNAME"'" --gtk-version=3 "$@"' >> AppRun
            chmod +x AppRun
            cp ../.desktop $PRODUCT.desktop
            cp ../icon.png icon.png
            cd ..
            ./appimagetool $PRODUCT.AppDir dist/$PRODUCT-${VERSION}.linux.AppImage
            
            # Create packaging structure for DEB and RPM (uses AppRun wrapper)
            mkdir -p packaging/opt/"$PRODUCT" packaging/usr/share/applications packaging/usr/share/icons/hicolor/256x256/apps packaging/usr/bin
            cp -r $PRODUCT.AppDir/* packaging/opt/"$PRODUCT"/
            cp packaging/opt/"$PRODUCT"/"$PRODUCT".desktop packaging/usr/share/applications/
            cp packaging/opt/"$PRODUCT"/icon.png packaging/usr/share/icons/hicolor/256x256/apps/"$PRODUCT".png
            ln -s /opt/"$PRODUCT"/AppRun packaging/usr/bin/"$BINNAME"
            sed -i "s/Exec=.*/Exec=\/usr\/bin\/$BINNAME %U/" packaging/usr/share/applications/"$PRODUCT".desktop
            sed -i "s/Icon=.*/Icon=$PRODUCT/" packaging/usr/share/applications/"$PRODUCT".desktop
             
            # Build DEB with fpm (add more --depends if needed)
            fpm -s dir -t deb -n "$PRODUCT" -v "$VERSION" -a amd64 -C packaging -p dist/"$PRODUCT"_"$VERSION"_amd64.deb --prefix / --depends libgtk-3-0 --depends libnss3 --depends libnotify4 --depends libxss1 --depends libgbm1 --depends libasound2 --depends libdbus-1-3
             
            # Build RPM with fpm (add more --depends if needed)
            fpm -s dir -t rpm -n "$PRODUCT" -v "$VERSION" -a x86_64 -C packaging -p dist/"$PRODUCT"-"$VERSION".x86_64.rpm --prefix / --depends gtk3 --depends nss --depends libnotify --depends libXScrnSaver --depends libgbm --depends alsa-lib --depends dbus-libs
             
          else
            npm run ${{ matrix.build_cmd }}
          fi
        shell: bash
  
      - name: Prepare Artifacts
        env:
          PRODUCT: ${{ matrix.product_name }}
        run: |
          mkdir -p out
          export npm_package_version=$(node -p "require('./package.json').version")
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            mv dist/$PRODUCT-$npm_package_version.ia32.exe out/$PRODUCT-$npm_package_version.win32.exe || true
            mv dist/$PRODUCT-$npm_package_version.x64.exe out/$PRODUCT-$npm_package_version.win64.exe || true
          else
            mv dist/* out/
          fi
        shell: bash

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: out/
          retention-days: 5

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create Tag
        if: github.event_name == 'workflow_dispatch'
        run: |
          git tag ${{ github.event.inputs.tag }}
          git push origin ${{ github.event.inputs.tag }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Debug Release Condition
        run: |
          echo "github.ref is ${{ github.ref }}"
          echo "Release job running for tag: ${{ github.event.inputs.tag || github.ref_name }}"
        shell: bash
        
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v2
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            artifacts/*/*.AppImage
            artifacts/*/*.deb
            artifacts/*/*.rpm
            artifacts/*/*.exe
            artifacts/*/*.dmg
            artifacts/*/*.zip
          tag_name: ${{ github.event.inputs.tag || github.ref_name }}
          name: Sip ${{ github.event.inputs.tag || github.ref_name }}
          body: "Automated Sip release for ${{ github.event.inputs.tag || github.ref_name }} - A MUD Client!"